// import { css } from '@emotion/react';
// import Head from 'next/head';
// import Image from 'next/image';
// import Link from 'next/link';
// import React, { useEffect, useState } from 'react';
// import Cookies from 'js-cookie';
// import { getParsedCookie, setParsedCookie } from '../../util/cookies';
// import { getDestinations } from '../../util/databaseHa';
// import ShareButton from '../../components/ShareButton';
// // import './destinations.css';

// // const productStyle = css`
// //   border: 1px solid #ddd;
// //   border-radius: 10px;
// //   padding: 20px;
// //   width: 20%;
// //   box-shadow: 4px 4px rgb(37, 150, 190);
// //   transition: 0.1s ease-in-out;
// //   :hover {
// //     transform: scale(106%);
// //   }
// // `;

// const animalsStyles = css`
//   a {
//     text-decoration: none;
//     color: #000000;
//     p {
//       color: #fff;
//       background-color: #3a8bcd;
//       padding: 5px;
//       display: inline-block;
//       border-radius: 5px;
//     }
//   }
//   color: black;
//   border-radius: 5px;
//   padding: 20px 30px;
//   & + & {
//     margin-top: 10px;
//   }
//   display: flex;
//   flex-wrap: wrap;
//   flex-direction: row;
//   justify-content: space-between;
// `;
// export default function Destinations(props) {
//   const [currentCoockie, setCurrentCoockie] = useState([]);

//   useEffect(() => {
//     setCurrentCoockie(
//       Cookies.get('wishList')?.length ? getParsedCookie('wishList') : [],
//     );
//   }, []);

//   const addRemoveToWishList = (id) => {
//     // let copyCurrCooki = [...currentCoockie];
//     // copyCurrCooki.push(id);

//     let tempCurrentCoockie = [...currentCoockie];
//     if (!currentCoockie.includes(id)) {
//       tempCurrentCoockie.push(id);
//       setCurrentCoockie(tempCurrentCoockie);
//       setParsedCookie('wishList', tempCurrentCoockie);
//     } else {
//       tempCurrentCoockie.splice(currentCoockie.indexOf(id), 1);
//       setCurrentCoockie(tempCurrentCoockie);
//       setParsedCookie('wishList', tempCurrentCoockie);
//     }
//   };

//   return (
//     <div>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <h1 className="text-center m-5">Pick your destinations</h1>

//       <div css={animalsStyles} class="card-group ">
//         {props.destination.map((place) => {
//           return (
//             <div class="card m-4 ">
//               <img src={`/${place.id}.jpg`} class="card-img-top" alt="..." />
//               <div class="card-body">
//                 <h5 className="card-title h5 ">
//                   {place.destination}
//                   <i class="far fa-heart"></i>
//                 </h5>
//                 <p class="card-text my-3">
//                   <i className="fas fa-map-marker-alt m-1" />
//                   {place.description}
//                 </p>
//               </div>
//               <div class="card-footer">
//                 <button
//                   className={
//                     currentCoockie.includes(place.id)
//                       ? 'btn btn-danger'
//                       : 'btn btn-outline-danger'
//                   }
//                   onClick={() => {
//                     addRemoveToWishList(place.id);
//                   }}
//                 >
//                   <svg
//                     xmlns="http://www.w3.org/2000/svg"
//                     width="16"
//                     height="16"
//                     fill="currentColor"
//                     class="bi bi-suit-heart"
//                     viewBox="0 0 16 16"
//                   >
//                     <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"></path>
//                   </svg>
//                   {currentCoockie.includes(place.id)
//                     ? 'Remove '
//                     : 'Add to WishList'}
//                 </button>
//                 <Link href={`/destinations/${place.id}`}>
//                   <button className="btn blue mt-3 d-inline-block">
//                     More <i class="fas fa-arrow-right"></i>
//                   </button>
//                 </Link>
//               </div>
//             </div>
//           );
//         })}
//       </div>
//     </div>
//   );
// }

// export async function getServerSideProps() {
//   const destination = await getDestinations();
//   return {
//     props: {
//       destination: destination,
//     },
//   };
// }

import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, { useEffect, useState } from 'react';
import Cookies from 'js-cookie';
import { getParsedCookie, setParsedCookie } from '../../util/cookies';
import { getDestinations } from '../../util/databaseHa';
import ShareButton from '../../components/ShareButton';
// import './destinations.css';

// const productStyle = css`
//   border: 1px solid #ddd;
//   border-radius: 10px;
//   padding: 20px;
//   width: 20%;
//   box-shadow: 4px 4px rgb(37, 150, 190);
//   transition: 0.1s ease-in-out;
//   :hover {
//     transform: scale(106%);
//   }
// `;

const animalsStyles = css`
  a {
    text-decoration: none;
    color: #000000;

    p {
      color: #fff;
      background-color: #3a8bcd;
      padding: 5px;
      display: inline-block;
      border-radius: 5px;
    }
  }
  color: black;
  border-radius: 5px;
  padding: 20px 30px;
  & + & {
    margin-top: 10px;
  }
  display: flex;
  flex-wrap: wrap;
  flex-direction: row;
  justify-content: space-between;
`;
export default function Destinations(props) {
  const [currentCoockie, setCurrentCoockie] = useState([]);

  useEffect(() => {
    setCurrentCoockie(
      Cookies.get('wishList')?.length ? getParsedCookie('wishList') : [],
    );
  }, []);

  const addRemoveToWishList = (id) => {
    // let copyCurrCooki = [...currentCoockie];
    // copyCurrCooki.push(id);

    let tempCurrentCoockie = [...currentCoockie];
    if (!currentCoockie.includes(id)) {
      tempCurrentCoockie.push(id);
      setCurrentCoockie(tempCurrentCoockie);
      setParsedCookie('wishList', tempCurrentCoockie);
    } else {
      tempCurrentCoockie.splice(currentCoockie.indexOf(id), 1);
      setCurrentCoockie(tempCurrentCoockie);
      setParsedCookie('wishList', tempCurrentCoockie);
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center m-5">Pick your destinations</h1>
      <div css={animalsStyles}>
        {props.destination.map((place) => {
          return (
            <div class="col m-3 destination" key={`destination-${place.id}`}>
              <div className=" card  cards h-100  ">
                <img src={`/${place.id}.jpg`} class="card-img-top" alt="..." />
                <div class="card-body">
                  <h5 className="card-title h5 ">
                    {place.destination}
                    <i class="far fa-heart"></i>
                  </h5>
                  <p class="card-text my-3">
                    <i className="fas fa-map-marker-alt m-1" />
                    {place.description}
                  </p>
                </div>
                <div class="card-footer">
                  <button
                    className={
                      currentCoockie.includes(place.id)
                        ? 'btn btn-danger'
                        : 'btn btn-outline-danger'
                    }
                    onClick={() => {
                      addRemoveToWishList(place.id);
                    }}
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-suit-heart"
                      viewBox="0 0 16 16"
                    >
                      <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"></path>
                    </svg>
                    {currentCoockie.includes(place.id)
                      ? 'Remove '
                      : 'Add to WishList'}
                  </button>
                  <Link href={`/destinations/${place.id}`}>
                    <button className="btn blue mt-3 d-inline-block">
                      More <i class="fas fa-arrow-right"></i>
                    </button>
                  </Link>
                </div>
              </div>
            </div>

            // <div
            //   className="col-md-2 mr-1 "
            //   // css={productStyle}
            //   key={`destination-${place.id}`}
            // >
            //   <Image src={`/${place.id}.jpg`} width="270" height="200" />
            //   <div class="card-description">
            //     <div class="card-title">
            //       <h4>{place.destination}</h4>
            //     </div>
            //     <div class="card-text">
            //       <p>{place.description}</p>
            //     </div>
            //     <div class="card-link">
            //       <button className="btn btn-primary mt-3">More</button>
            //     </div>
            //   </div>
            // </div>
            // <div className="container" key={`destination-${place.id}`}>
            //   <div className="row">
            //     <div className="col-md-3">
            //       <Image src={`/${place.id}.jpg`} width="370" height="300" />
            //       <div class="card-description">
            //         <div class="card-title">
            //           <h4>{place.destination}</h4>
            //         </div>
            //         <div class="card-text">
            //           <p>{place.description}</p>
            //         </div>
            //         <div class="card-link">
            //           <button className="btn btn-primary mt-3">More</button>
            //         </div>
            //       </div>{' '}
            //     </div>
            //   </div>
            // </div>
          );
        })}
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const destination = await getDestinations();
  return {
    props: {
      destination: destination,
    },
  };
}
