import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import { hotel } from '../util/database';
// import { getDestinations } from '../util/databaseHa';

const productStyle = css`
  border: 1px solid #ddd;
  border-radius: 10px;
  padding: 20px;
  width: 20%;
  box-shadow: 4px 4px rgb(37, 150, 190);
  transition: 0.1s ease-in-out;
  :hover {
    transform: scale(106%);
  }
`;

const animalsStyles = css`
  a {
    text-decoration: none;
    color: #000000;

    p {
      color: #fff;
      background-color: #3a8bcd;
      padding: 5px;
      display: inline-block;
      border-radius: 5px;
    }
  }
  color: black;
  border-radius: 5px;
  padding: 20px 30px;
  & + & {
    margin-top: 10px;
  }
  display: flex;
  flex-wrap: wrap;
  flex-direction: row;
  justify-content: space-between;
`;
export default function Hotel(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center m-5">Pick your destinations</h1>

      <div css={animalsStyles}>
        {props.hotel.map((place) => {
          return (
            <div css={productStyle} key={`hotel-${place.id}`}>
              <Link href={`/hotel/${place.id}`}>
                <a>
                  <Image src={`/${place.id}.jpg`} width="370" height="300" />

                  <div> Destination:{place.name}</div>

                  <div> Description:{place.night}</div>
                  <button className="btn btn-primary mt-3">More</button>
                </a>
              </Link>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export function getServerSideProps() {
  // const destination = await getDestinations();
  return {
    props: {
      hotel: hotel,
    },
  };
}
