import Head from 'next/head';
import { useEffect } from 'react';
import Header from '../components/Header';

type Props = {
  refreshUserProfile: () => Promise<void>;
};

export default function Home(props: Props) {
  useEffect(() => {
    props.refreshUserProfile().catch(() => console.log('resfersh user failed'));
  }, [props]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      </main>
    </div>
  );
}
