import React from 'react';
import Layout from '../components/Layout';
import Head from 'next/head';
import { css } from '@emotion/react';

const style = css`
  min-height: 500px;
  display: flex;
  justify-content: center;
  align-items: center;
  background-image: linear-gradient(
      rgba(14, 174, 248, 0.7),
      rgba(181, 225, 245, 0.7)
    ),
    url(/bg.jpg);
`;

const ul = css`
  margin: 0;
  padding: 0;
  display: flex;
  text-align: center;
  li {
    list-style: none;

    backdrop-filter: blur(5px);
    box-shadow: 0 25px 45px rgba(0, 0, 0, 0.1);
    border: 1px solid rgba(255, 255, 255, 0.2);
    border-right: 1px solid rgba(255, 255, 255, 0.5);
    border-bottom: 1px solid rgba(255, 255, 255, 0.2);

    color: #fff;
    padding: 10px 10px;
    font-size: 5rem;
    font-weight: bold;
    letter-spacing: 10px;
    transition: 2s;
    margin-right: 2px;
  }
  &:hover li {
    transform: rotate(45deg) translateY(-200px);
    opacity: 0;
    filter: blur(20px);
    &:nth-child(1) {
      transition-delay: 0;
    }

    &:nth-child(2) {
      transition-delay: 0.3s;
    }

    &:nth-child(3) {
      transition-delay: 0.6s;
    }

    &:nth-child(4) {
      transition-delay: 0.9s;
    }

    &:nth-child(5) {
      transition-delay: 1.2s;
    }
    &:nth-child(6) {
      transition-delay: 1.5s;
    }
    &:nth-child(7) {
      transition-delay: 1.8s;
    }
    &:nth-child(8) {
      transition-delay: 2.1s;
    }
    &:nth-child(9) {
      transition-delay: 2.4s;
    }
  }
`;

function thankyou() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
        <script
          src="https://code.jquery.com/jquery-3.6.0.slim.js"
          integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY="
          crossOrigin="anonymous"
        />
        <link rel="stylesheet" href="css/owl.carousel.min.css" />
        <link rel="stylesheet" href="css/owl.theme.default.min.css" />
      </Head>
      <main css={style}>
        <ul css={ul}>
          <li>T</li>
          <li>H</li>
          <li>A</li>
          <li>N</li>
          <li>K</li>
          <li>&nbsp;</li>
          <li>Y</li>
          <li>O</li>
          <li>U</li>
        </ul>
      </main>
    </div>
  );
}

export default thankyou;

{
  /* <div>
  <section className="login">
    <div className="color"></div>
    <div className="color"></div>
    <div className="color"></div>
    <div className="box">
      <div className="square"></div>
      <div className="square"></div>
      <div className="square"></div>
      <div className="square"></div>
      <div className="square"></div>

      <div className="login-container">
        <div className="form">
          <h2>Login Form</h2>
          <form>
            <label>
              username:
              <input
                value={username}
                onChange={(event) => {
                  setUsername(event.currentTarget.value);
                }}
              />
            </label>
            <label>
              password:{' '}
              <input
                value={password}
                onChange={(event) => {
                  setPassword(event.currentTarget.value);
                }}
              />
            </label>
            <button onClick={() => loginHandler()}>Login</button>
            {errors.map((error) => (
              <div key={`error-${error.message}`}>{error.message}</div>
            ))}
          </form>
        </div>
      </div>
    </div>
  </section>
</div>; */
}
